server {
    listen 80;
    server_name _;

    root /var/www/duovet;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Content-Security-Policy "default-src 'self' https: http: data: blob: 'unsafe-inline' 'unsafe-eval'; script-src 'self' https: http: data: blob: 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https: http: data: blob: 'unsafe-inline'; img-src 'self' https: http: data: blob: 'unsafe-inline'; style-src 'self' https: http: data: blob: 'unsafe-inline'; frame-src 'self' https: http: data: blob;" always;
        add_header Access-Control-Allow-Origin *;
    }

    location /api {
        proxy_pass http://127.0.0.1:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
